#!/usr/bin/env python3
"""
Setup script for environment configuration
"""

import os
from pathlib import Path

def create_env_file():
    """Create a .env file with user input."""
    env_file = Path(".env")
    
    if env_file.exists():
        print("✅ .env file already exists")
        return
    
    print("🔧 Setting up environment configuration...")
    print("=" * 50)
    
    # Get API key from user
    api_key = input("Enter your Anthropic API key (starts with 'sk-ant-'): ").strip()
    
    if not api_key:
        print("❌ No API key provided")
        return
    
    if not api_key.startswith('sk-ant-'):
        print("❌ Invalid API key format. Should start with 'sk-ant-'")
        return
    
    # Create .env content
    env_content = f"""# Anthropic API Configuration
# Generated by setup script
ANTHROPIC_API_KEY={api_key}

# Other configuration
MAX_TOKENS=10000
TEMPERATURE=0.7
"""
    
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        
        print(f"✅ Created .env file: {env_file}")
        print("🔑 API key saved successfully")
        print("💡 You can now run the cheatsheet generator without exporting environment variables!")
        
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")


if __name__ == "__main__":
    create_env_file() 