author: Your Name
copyright_start_year: 2025
organization: TheoryHub
output_formats:
- pdf
- html
pandoc:
  pdf_engine: xelatex
  template: templates/styles/custom.latex
  variables:
    colorlinks: true
    fontfamily: libertine
    geometry: margin=1in
