name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: '0.8.13'
        enable-cache: true

    - name: Install the project into uv
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: |
        uv run pytest tests/ -n auto

    - name: Minimise uv cache for CI
      run: uv cache prune --ci
